using Everaldo.Cardoso.C19BR.Framework.Models;
using System.Collections.Generic;

namespace Everaldo.Cardoso.C19BR.Framework.ToolBox
{
    public static class CountriesOfWorld
    {

        public static List<Country> getCountriesOfWorld()
        {
            return new List<Country>
            {
                new Country{ NameEn = "USA", NamePT = "EUA" },
                new Country{ NameEn = "SPAIN", NamePT = "ESPANHA" },
                new Country{ NameEn = "ITALY", NamePT = "ITÁLIA" },
                new Country{ NameEn = "FRANCE", NamePT = "FRANÇA" },
                new Country{ NameEn = "GERMANY", NamePT = "ALEMANHA" },
                new Country{ NameEn = "UK", NamePT = "REINO UNIDO" },
                new Country{ NameEn = "CHINA", NamePT = "CHINA" },
                new Country{ NameEn = "IRAN", NamePT = "IRÃ" },
                new Country{ NameEn = "TURKEY", NamePT = "TURQUIA" },
                new Country{ NameEn = "BELGIUM", NamePT = "BÉLGICA" },
                new Country{ NameEn = "BRAZIL", NamePT = "BRASIL" },
                new Country{ NameEn = "CANADA", NamePT = "CANADÁ" },
                new Country{ NameEn = "NETHERLANDS", NamePT = "PAÍSES BAIXOS" },
                new Country{ NameEn = "RUSSIA", NamePT = "RÚSSIA" },
                new Country{ NameEn = "SWITZERLAND", NamePT = "SUÍÇA" },
                new Country{ NameEn = "PORTUGAL", NamePT = "PORTUGAL" },
                new Country{ NameEn = "AUSTRIA", NamePT = "ÁUSTRIA" },
                new Country{ NameEn = "IRELAND", NamePT = "IRLANDA" },
                new Country{ NameEn = "INDIA", NamePT = "ÍNDIA" },
                new Country{ NameEn = "ISRAEL", NamePT = "ISRAEL" },
                new Country{ NameEn = "SWEDEN", NamePT = "SUÉCIA" },
                new Country{ NameEn = "PERU", NamePT = "PERU" },
                new Country{ NameEn = "S. KOREA", NamePT = "S. CORÉIA" },
                new Country{ NameEn = "CHILE", NamePT = "CHILE" },
                new Country{ NameEn = "JAPAN", NamePT = "JAPÃO" },
                new Country{ NameEn = "ECUADOR", NamePT = "EQUADOR" },
                new Country{ NameEn = "POLAND", NamePT = "POLÔNIA" },
                new Country{ NameEn = "ROMANIA", NamePT = "ROMÊNIA" },
                new Country{ NameEn = "PAKISTAN", NamePT = "PAQUISTÃO" },
                new Country{ NameEn = "DENMARK", NamePT = "DINAMARCA" },
                new Country{ NameEn = "NORWAY", NamePT = "NORUEGA" },
                new Country{ NameEn = "AUSTRALIA", NamePT = "AUSTRÁLIA" },
                new Country{ NameEn = "SAUDI ARABIA", NamePT = "ARÁBIA SAUDITA" },
                new Country{ NameEn = "CZECHIA", NamePT = "CHÉQUIA" },
                new Country{ NameEn = "MEXICO", NamePT = "MÉXICO" },
                new Country{ NameEn = "PHILIPPINES", NamePT = "FILIPINAS" },
                new Country{ NameEn = "INDONESIA", NamePT = "INDONÉSIA" },
                new Country{ NameEn = "SERBIA", NamePT = "SÉRVIA E MONTENEGRO" },
                new Country{ NameEn = "MALAYSIA", NamePT = "MALÁSIA" },
                new Country{ NameEn = "SINGAPORE", NamePT = "CINGAPURA" },
                new Country{ NameEn = "BELARUS", NamePT = "BELARUS" },
                new Country{ NameEn = "UKRAINE", NamePT = "UCRÂNIA" },
                new Country{ NameEn = "QATAR", NamePT = "CATAR" },
                new Country{ NameEn = "DOMINICAN REPUBLIC", NamePT = "REPÚBLICA DOMINICANA" },
                new Country{ NameEn = "PANAMA", NamePT = "PANAMÁ" },
                new Country{ NameEn = "LUXEMBOURG", NamePT = "LUXEMBURGO" },
                new Country{ NameEn = "FINLAND", NamePT = "FINLÂNDIA" },
                new Country{ NameEn = "COLOMBIA", NamePT = "COLÔMBIA" },
                new Country{ NameEn = "EGYPT", NamePT = "EGITO" },
                new Country{ NameEn = "THAILAND", NamePT = "TAILÂNDIA" },
                new Country{ NameEn = "SOUTH AFRICA", NamePT = "ÁFRICA DO SUL" },
                new Country{ NameEn = "ARGENTINA", NamePT = "ARGENTINA" },
                new Country{ NameEn = "MOROCCO", NamePT = "MARROCOS" },
                new Country{ NameEn = "ALGERIA", NamePT = "ARGÉLIA" },
                new Country{ NameEn = "GREECE", NamePT = "GRÉCIA" },
                new Country{ NameEn = "CROATIA", NamePT = "CROÁCIA" },
                new Country{ NameEn = "ICELAND", NamePT = "ISLÂNDIA" },
                new Country{ NameEn = "BAHRAIN", NamePT = "BAHREIN" },
                new Country{ NameEn = "HUNGARY", NamePT = "HUNGRIA" },
                new Country{ NameEn = "BANGLADESH", NamePT = "BANGLADESH" },
                new Country{ NameEn = "KUWAIT", NamePT = "KUAITE" },
                new Country{ NameEn = "ESTONIA", NamePT = "ESTÔNIA" },
                new Country{ NameEn = "IRAQ", NamePT = "IRAQUE" },
                new Country{ NameEn = "KAZAKHSTAN", NamePT = "CAZAQUISTÃO" },
                new Country{ NameEn = "NEW ZEALAND", NamePT = "NOVA ZELÂNDIA" },
                new Country{ NameEn = "UZBEKISTAN", NamePT = "UZBEQUISTÃO" },
                new Country{ NameEn = "AZERBAIJAN", NamePT = "AZERBAIJÃO" },
                new Country{ NameEn = "SLOVENIA", NamePT = "ESLOVÊNIA" },
                new Country{ NameEn = "BOSNIA AND HERZEGOVINA", NamePT = "BÓSNIA E HERZEGOVINA" },
                new Country{ NameEn = "ARMENIA", NamePT = "ARMÊNIA" },
                new Country{ NameEn = "LITHUANIA", NamePT = "LITUÂNIA" },
                new Country{ NameEn = "OMAN", NamePT = "OMÃ" },
                new Country{ NameEn = "HONG KONG", NamePT = "HONG KONG" },
                new Country{ NameEn = "CAMEROON", NamePT = "CAMARÕES" },
                new Country{ NameEn = "SLOVAKIA", NamePT = "ESLOVÁQUIA" },
                new Country{ NameEn = "CUBA", NamePT = "CUBA" },
                new Country{ NameEn = "AFGHANISTAN", NamePT = "AFEGANISTÃO" },
                new Country{ NameEn = "TUNISIA", NamePT = "TUNÍSIA" },
                new Country{ NameEn = "BULGARIA", NamePT = "BULGÁRIA" },
                new Country{ NameEn = "CYPRUS", NamePT = "CHIPRE" },
                new Country{ NameEn = "LATVIA", NamePT = "LETÔNIA" },
                new Country{ NameEn = "ANDORRA", NamePT = "ANDORRA" },
                new Country{ NameEn = "LEBANON", NamePT = "LÍBANO" },
                new Country{ NameEn = "COSTA RICA", NamePT = "COSTA RICA" },
                new Country{ NameEn = "GHANA", NamePT = "GANA" },
                new Country{ NameEn = "DJIBOUTI", NamePT = "DJIBOUTI" },
                new Country{ NameEn = "NIGER", NamePT = "NÍGER" },
                new Country{ NameEn = "BURKINA FASO", NamePT = "BURKINA FASO" },
                new Country{ NameEn = "ALBANIA", NamePT = "ALBÂNIA" },
                new Country{ NameEn = "URUGUAY", NamePT = "URUGUAI" },
                new Country{ NameEn = "KYRGYZSTAN", NamePT = "QUIRGUISTÃO" },
                new Country{ NameEn = "NIGERIA", NamePT = "NIGÉRIA" },
                new Country{ NameEn = "GUINEA", NamePT = "GUINÉ" },
                new Country{ NameEn = "HONDURAS", NamePT = "HONDURAS" },
                new Country{ NameEn = "SAN MARINO", NamePT = "SAN MARINO" },
                new Country{ NameEn = "MALTA", NamePT = "MALTA" },
                new Country{ NameEn = "JORDAN", NamePT = "JORDÂNIA" },
                new Country{ NameEn = "RÉUNION", NamePT = "REUNIÃO" },
                new Country{ NameEn = "GEORGIA", NamePT = "GEÓRGIA" },
                new Country{ NameEn = "SENEGAL", NamePT = "SENEGAL" },
                new Country{ NameEn = "MAURITIUS", NamePT = "MAURÍCIA" },
                new Country{ NameEn = "MONTENEGRO", NamePT = "MONTENEGRO" },
                new Country{ NameEn = "ISLE OF MAN", NamePT = "ILHA DO HOMEM" },
                new Country{ NameEn = "VIETNAM", NamePT = "VIETNÃ" },
                new Country{ NameEn = "SRI LANKA", NamePT = "SRI LANKA" },
                new Country{ NameEn = "KENYA", NamePT = "QUÊNIA" },
                new Country{ NameEn = "MAYOTTE", NamePT = "MAYOTTE" },
                new Country{ NameEn = "VENEZUELA", NamePT = "VENEZUELA" },
                new Country{ NameEn = "GUATEMALA", NamePT = "GUATEMALA" },
                new Country{ NameEn = "PARAGUAY", NamePT = "PARAGUAI" },
                new Country{ NameEn = "MALI", NamePT = "MALI" },
                new Country{ NameEn = "EL SALVADOR", NamePT = "EL SALVADOR" },
                new Country{ NameEn = "MARTINIQUE", NamePT = "MARTINICA" },
                new Country{ NameEn = "GUADELOUPE", NamePT = "GUADALUPE" },
                new Country{ NameEn = "JAMAICA", NamePT = "JAMAICA" },
                new Country{ NameEn = "RWANDA", NamePT = "RUANDA" },
                new Country{ NameEn = "GIBRALTAR", NamePT = "GIBRALTAR" },
                new Country{ NameEn = "CAMBODIA", NamePT = "CAMBOJA" },
                new Country{ NameEn = "CONGO", NamePT = "CONGO" },
                new Country{ NameEn = "TRINIDAD AND TOBAGO", NamePT = "TRINIDAD E TOBAGO" },
                new Country{ NameEn = "MADAGASCAR", NamePT = "MADAGASCAR" },
                new Country{ NameEn = "ARUBA", NamePT = "ARUBA" },
                new Country{ NameEn = "MONACO", NamePT = "MONACO" },
                new Country{ NameEn = "ETHIOPIA", NamePT = "ETIÓPIA" },
                new Country{ NameEn = "FRENCH GUIANA", NamePT = "GUIANA FRANCESA" },
                new Country{ NameEn = "MYANMAR", NamePT = "MYANMAR" },
                new Country{ NameEn = "BERMUDA", NamePT = "BERMUDA" },
                new Country{ NameEn = "TOGO", NamePT = "TOGO" },
                new Country{ NameEn = "GABON", NamePT = "GABÃO" },
                new Country{ NameEn = "SOMALIA", NamePT = "SOMÁLIA" },
                new Country{ NameEn = "LIECHTENSTEIN", NamePT = "LIECHTENSTEIN" },
                new Country{ NameEn = "BARBADOS", NamePT = "BARBADOS" },
                new Country{ NameEn = "CAYMAN ISLANDS", NamePT = "ILHAS CAYMAN" },
                new Country{ NameEn = "LIBERIA", NamePT = "LIBÉRIA" },
                new Country{ NameEn = "FRENCH POLYNESIA", NamePT = "POLINÉSIA FRANCESA" },
                new Country{ NameEn = "GUYANA", NamePT = "GUIANA" },
                new Country{ NameEn = "UGANDA", NamePT = "UGANDA" },
                new Country{ NameEn = "BAHAMAS", NamePT = "BAHAMAS" },
                new Country{ NameEn = "EQUATORIAL GUINEA", NamePT = "GUINÉ EQUATORIAL" },
                new Country{ NameEn = "LIBYA", NamePT = "LÍBIA" },
                new Country{ NameEn = "ZAMBIA", NamePT = "ZÂMBIA" },
                new Country{ NameEn = "MACAO", NamePT = "MACAU" },
                new Country{ NameEn = "GUINEA-BISSAU", NamePT = "GUINÉ-BISSAU" },
                new Country{ NameEn = "HAITI", NamePT = "HAITI" },
                new Country{ NameEn = "PUERTO RICO", NamePT = "PORTO RICO" },
                new Country{ NameEn = "BENIN", NamePT = "BENIN" },
                new Country{ NameEn = "ERITREA", NamePT = "ERITREIA" },
                new Country{ NameEn = "SYRIA", NamePT = "SÍRIA" },
                new Country{ NameEn = "GUAM", NamePT = "GUAM" },
                new Country{ NameEn = "SUDAN", NamePT = "SUDÃO" },
                new Country{ NameEn = "MONGOLIA", NamePT = "MONGÓLIA" },
                new Country{ NameEn = "MOZAMBIQUE", NamePT = "MOÇAMBIQUE" },
                new Country{ NameEn = "CHAD", NamePT = "CHAD" },
                new Country{ NameEn = "ANTIGUA AND BARBUDA", NamePT = "ANTÍGUA E BARBUDA" },
                new Country{ NameEn = "MALDIVES", NamePT = "MALDIVAS" },
                new Country{ NameEn = "ZIMBABWE", NamePT = "ZIMBÁBUE" },
                new Country{ NameEn = "ANGOLA", NamePT = "ANGOLA" },
                new Country{ NameEn = "BELIZE", NamePT = "BELIZE" },
                new Country{ NameEn = "NEW CALEDONIA", NamePT = "NOVA CALEDONIA" },
                new Country{ NameEn = "TIMOR-LESTE", NamePT = "TIMOR-LESTE" },
                new Country{ NameEn = "FIJI", NamePT = "FIJI" },
                new Country{ NameEn = "U.S. VIRGIN ISLANDS", NamePT = "ILHAS VIRGENS AMERICANAS" },
                new Country{ NameEn = "DOMINICA", NamePT = "DOMINICA" },
                new Country{ NameEn = "MALAWI", NamePT = "MALAWI" },
                new Country{ NameEn = "NAMIBIA", NamePT = "NAMÍBIA" },
                new Country{ NameEn = "NEPAL", NamePT = "NEPAL" },
                new Country{ NameEn = "BOTSWANA", NamePT = "BOTSWANA" },
                new Country{ NameEn = "SAINT LUCIA", NamePT = "SANTA LÚCIA" },
                new Country{ NameEn = "SIERRA LEONE", NamePT = "SERRA LEOA" },
                new Country{ NameEn = "CURAÇAO", NamePT = "CURAÇAO" },
                new Country{ NameEn = "GRENADA", NamePT = "GRANADA" },
                new Country{ NameEn = "SAINT KITTS AND NEVIS", NamePT = "SÃO CRISTÓVÃO E NEVIS" },
                new Country{ NameEn = "GREENLAND", NamePT = "GRONELÂNDIA" },
                new Country{ NameEn = "SEYCHELLES", NamePT = "SEYCHELLES" },
                new Country{ NameEn = "MONTSERRAT", NamePT = "MONTSERRAT" },
                new Country{ NameEn = "SURINAME", NamePT = "SURINAME" },
                new Country{ NameEn = "GAMBIA", NamePT = "GÂMBIA" },
                new Country{ NameEn = "NICARAGUA", NamePT = "NICARÁGUA" },
                new Country{ NameEn = "MAURITANIA", NamePT = "MAURITÂNIA" },
                new Country{ NameEn = "PAPUA NEW GUINEA", NamePT = "PAPUA-NOVA GUINÉ" },
                new Country{ NameEn = "WESTERN SAHARA", NamePT = "SAHARA OCIDENTAL" },
                new Country{ NameEn = "BHUTAN", NamePT = "BUTÃO" },
                new Country{ NameEn = "BURUNDI", NamePT = "BURUNDI" },
                new Country{ NameEn = "SOUTH SUDAN", NamePT = "SUDÃO DO SUL" },
                new Country{ NameEn = "SAO TOME AND PRINCIPE", NamePT = "SAO TOME E PRINCIPE" },
                new Country{ NameEn = "ANGUILLA", NamePT = "ANGUILLA" },
                new Country{ NameEn = "YEMEN", NamePT = "IÊMEN" },
                new Country{ NameEn = "ÅLAND ISLANDS", NamePT = "ILHAS ÅLAND" },
                new Country{ NameEn = "AMERICAN SAMOA", NamePT = "SAMOA AMERICANA" },
                new Country{ NameEn = "ANTARCTICA", NamePT = "ANTÁRTIDA" },
                new Country{ NameEn = "BRUNEI DARUSSALAM", NamePT = "BRUNEI DARUSSALAM" },
                new Country{ NameEn = "BONAIRE, SINT EUSTATIUS AND SABA", NamePT = "BONAIRE, SINT EUSTATIUS E SABA" },
                new Country{ NameEn = "BRITISH INDIAN OCEAN TERRITORY", NamePT = "TERRITÓRIO BRITÂNICO DO OCEANO ÍNDICO" },
                new Country{ NameEn = "BOLIVIA, PLURINATIONAL STATE OF", NamePT = "BOLÍVIA, ESTADO PLURINACIONAL DE" },
                new Country{ NameEn = "CENTRAL AFRICAN REPUBLIC", NamePT = "REPÚBLICA CENTRO-AFRICANA" },
                new Country{ NameEn = "BOUVET ISLAND", NamePT = "ILHA BOUVET" },
                new Country{ NameEn = "COCOS (KEELING) ISLANDS", NamePT = "ILHAS COCOS (KEELING)" },
                new Country{ NameEn = "CAPE VERDE", NamePT = "CABO VERDE" },
                new Country{ NameEn = "COOK ISLANDS", NamePT = "ILHAS COOK" },
                new Country{ NameEn = "CHRISTMAS ISLAND", NamePT = "ILHA DE NATAL" },
                new Country{ NameEn = "COMOROS", NamePT = "COMORES" },
                new Country{ NameEn = "CONGO, THE DEMOCRATIC REPUBLIC OF THE", NamePT = "CONGO, A REPÚBLICA DEMOCRÁTICA DO" },
                new Country{ NameEn = "CÔTE D'IVOIRE", NamePT = "COSTA DO MARFIM" },
                new Country{ NameEn = "FAROE ISLANDS", NamePT = "ILHAS FAROÉS" },
                new Country{ NameEn = "FRENCH SOUTHERN TERRITORIES", NamePT = "TERRITÓRIOS DO SUL DA FRANÇA" },
                new Country{ NameEn = "FALKLAND ISLANDS (MALVINAS)", NamePT = "ILHAS FALKLAND (MALVINAS)" },
                new Country{ NameEn = "HOLY SEE (VATICAN CITY STATE)", NamePT = "SANTA SÉ (ESTADO DO VATICANO)" },
                new Country{ NameEn = "GUERNSEY", NamePT = "GUERNSEY" },
                new Country{ NameEn = "HEARD ISLAND AND MCDONALD ISLANDS", NamePT = "ILHA OUVIDA E ILHAS MCDONALD" },
                new Country{ NameEn = "JERSEY", NamePT = "JERSEY" },
                new Country{ NameEn = "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", NamePT = "COREIA, REPÚBLICA DEMOCRÁTICA DO POVO" },
                new Country{ NameEn = "NIUE", NamePT = "NIUE" },
                new Country{ NameEn = "MARSHALL ISLANDS", NamePT = "ILHAS MARSHALL" },
                new Country{ NameEn = "KIRIBATI", NamePT = "KIRIBATI" },
                new Country{ NameEn = "LAO PEOPLE'S DEMOCRATIC REPUBLIC", NamePT = "REPÚBLICA DEMOCRÁTICA DO POVO DE LAO" },
                new Country{ NameEn = "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", NamePT = "MACEDÔNIA, A ANTIGA REPÚBLICA IUGOSLÁVIA DE" },
                new Country{ NameEn = "MOLDOVA, REPUBLIC OF", NamePT = "MOLDÁVIA, REPÚBLICA DA" },
                new Country{ NameEn = "NORFOLK ISLAND", NamePT = "ILHA NORFOLK" },
                new Country{ NameEn = "PALAU", NamePT = "PALAU" },
                new Country{ NameEn = "SVALBARD AND JAN MAYEN", NamePT = "SVALBARD E JAN MAYEN" },
                new Country{ NameEn = "SAINT MARTIN (FRENCH PART)", NamePT = "SAINT MARTIN (PARTE FRANCESA)" },
                new Country{ NameEn = "TAIWAN, PROVINCE OF CHINA", NamePT = "TAIWAN, PROVÍNCIA DA CHINA" },
                new Country{ NameEn = "SOLOMON ISLANDS", NamePT = "ILHAS SALOMÃO" },
                new Country{ NameEn = "SWAZILAND", NamePT = "SUAZILÂNDIA" },
                new Country{ NameEn = "VIRGIN ISLANDS, BRITISH", NamePT = "ILHAS VIRGENS BRITÂNICAS" },
                new Country{ NameEn = "TAJIKISTAN", NamePT = "TAJIQUISTÃO" },
                new Country{ NameEn = "TOKELAU", NamePT = "TOKELAU" },
                new Country{ NameEn = "TURKMENISTAN", NamePT = "TURQUEMENISTÃO" },
                new Country{ NameEn = "UNITED ARAB EMIRATES", NamePT = "EMIRADOS ÁRABES UNIDOS" },
                new Country{ NameEn = "LESOTHO", NamePT = "LESOTO" },
                new Country{ NameEn = "MICRONESIA, FEDERATED STATES OF", NamePT = "MICRONÉSIA, ESTADOS FEDERADOS DE" },
                new Country{ NameEn = "NAURU", NamePT = "NAURU" },
                new Country{ NameEn = "NORTHERN MARIANA ISLANDS", NamePT = "ILHAS MARIANAS DO NORTE" },
                new Country{ NameEn = "PITCAIRN", NamePT = "PITCAIRN" },
                new Country{ NameEn = "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA", NamePT = "SÃO HELENA, ASCENSÃO E TRISSTÃO DA CUNHA" },
                new Country{ NameEn = "SAINT VINCENT AND THE GRENADINES", NamePT = "SÃO VICENTE E GRANADINAS" },
                new Country{ NameEn = "SINT MAARTEN (DUTCH PART)", NamePT = "SINT MAARTEN (PARTE HOLANDESA)" },
                new Country{ NameEn = "TUVALU", NamePT = "TUVALU" },
                new Country{ NameEn = "SAMOA", NamePT = "SAMOA" },
                new Country{ NameEn = "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", NamePT = "GEÓRGIA DO SUL E ILHAS SANDUÍCHE DO SUL" },
                new Country{ NameEn = "UNITED STATES MINOR OUTLYING ISLANDS", NamePT = "ILHAS MENORES DOS ESTADOS UNIDOS" },
                new Country{ NameEn = "PALESTINE, STATE OF", NamePT = "PALESTINA, ESTADO DE" },
                new Country{ NameEn = "SAINT BARTHÉLEMY", NamePT = "SÃO BARTHÉLEMY" },
                new Country{ NameEn = "SAINT PIERRE AND MIQUELON", NamePT = "SAINT PIERRE E MIQUELON" },
                new Country{ NameEn = "TANZANIA, UNITED REPUBLIC OF", NamePT = "TANZÂNIA, REPÚBLICA UNIDA DE" },
                new Country{ NameEn = "TONGA", NamePT = "TONGA" },
                new Country{ NameEn = "TURKS AND CAICOS ISLANDS", NamePT = "ILHAS TURKS E CAICOS" },
                new Country{ NameEn = "VANUATU", NamePT = "VANUATU" },
                new Country{ NameEn = "WALLIS AND FUTUNA", NamePT = "WALLIS E FUTUNA" }
            };
        }
    }
}
