using Everaldo.Cardoso.C19BR.Framework.Enums;

namespace Everaldo.Cardoso.C19BR.Domain.Enums
{
    public enum States
    {
        [EnumValue("AC")]
        AC,
        [EnumValue("AL")]
        AL,
        [EnumValue("AP")]
        AP,
        [EnumValue("AM")]
        AM,
        [EnumValue("BA")]
        BA,
        [EnumValue("CE")]
        CE,
        [EnumValue("DF")]
        DF,
        [EnumValue("ES")]
        ES,
        [EnumValue("MA")]
        MA,
        [EnumValue("GO")]
        GO,
        [EnumValue("MT")]
        MT,
        [EnumValue("MS")]
        MS,
        [EnumValue("MG")]
        MG,
        [EnumValue("PA")]
        PA,
        [EnumValue("PB")]
        PB,
        [EnumValue("PR")]
        PR,
        [EnumValue("PE")]
        PE,
        [EnumValue("PI")]
        PI,
        [EnumValue("RJ")]
        RJ,
        [EnumValue("RN")]
        RN,
        [EnumValue("RS")]
        RS,
        [EnumValue("RO")]
        RO,
        [EnumValue("RR")]
        RR,
        [EnumValue("SC")]
        SC,
        [EnumValue("SP")]
        SP,
        [EnumValue("SE")]
        SE,
        [EnumValue("TO")]
        TO
    }
}
